import { scenarioSchema, template, type Scenario } from "./training";

const map = { lat: 51.23, lng: 6.78, zoom: 15, tiles: "", attribution: "" };
const route = [
  { lat: 51.23, lng: 6.78 },
  { lat: 51.233, lng: 6.786 },
];
const base = {
  version: 2 as const,
  mode: "LIVE" as const,
  seed: 2048,
  map,
  stations: [] as Scenario["stations"],
  patients: [] as Scenario["patients"],
  props: [] as Scenario["props"],
  dossiers: [] as Scenario["dossiers"],
  teams: [] as Scenario["teams"],
  actors: [] as Scenario["actors"],
  zones: [] as Scenario["zones"],
  injects: [] as Scenario["injects"],
  objectives: [] as Scenario["objectives"],
};
const build = (name: string, patch: Record<string, unknown>): Scenario =>
  scenarioSchema.parse({ ...base, name, ...patch });

// One registry for every mission template: wizard quick picks, the gallery and
// the mission library all read from here. `template(kind)` in training.ts stays
// a low-level default factory (used by `newState`), not a second catalog.
export type MissionCategory = "starter" | "airsoft" | "film" | "professional";

export type MissionTemplate = {
  id: string;
  name: string;
  summary: string;
  category: MissionCategory;
  difficulty: 1 | 2 | 3;
  durationMin: number;
  scenario: Scenario;
};

export const missionTemplates: MissionTemplate[] = [
  {
    id: "blank",
    name: "Blank Mission",
    summary: "Free canvas without devices or entities.",
    category: "starter",
    difficulty: 1,
    durationMin: 0,
    scenario: build("Blank Mission", {}),
  },
  {
    id: "eod-disposal",
    name: "Ordnance Disposal",
    summary: "Fictional console, cordon and maintenance stages.",
    category: "professional",
    difficulty: 3,
    durationMin: 25,
    scenario: build("Ordnance Disposal", {
      stations: [
        { id: "hq", name: "Command", role: "hq", module: "tracking" },
        {
          id: "ord-1",
          name: "Console 01",
          role: "element",
          module: "ordnance",
          bindings: { patient: "", prop: "ordnance-1", objective: "" },
        },
        { id: "term-1", name: "Maintenance Terminal", role: "element", module: "terminal" },
        { id: "data-1", name: "Data Sheet", role: "element", module: "data-sheet" },
        { id: "cam-1", name: "Camera 01", role: "element", module: "camera" },
      ],
      props: [
        {
          id: "ordnance-1",
          kind: "ordnance",
          name: "Assembly 09",
          states: ["armed", "bypassed", "disarmed", "tampered"],
          initial: "armed",
          visible: true,
        },
      ],
      zones: [{ id: "zone-1", name: "Cordon", lat: 51.233, lng: 6.786, radius: 150 }],
      objectives: [
        { id: "obj-1", name: "Report cordon" },
        { id: "obj-2", name: "Complete diagnostics" },
        { id: "obj-3", name: "Disarm assembly" },
      ],
      injects: [
        {
          id: "inj-1",
          name: "Time window running",
          trigger: "timer",
          at: 600,
          actions: [{ type: "message", text: "Time window running" }],
          enabled: true,
        },
      ],
    }),
  },
  {
    id: "data-exfiltration",
    name: "Data Exfiltration",
    summary: "Target system, archive and exfiltration from the target area.",
    category: "professional",
    difficulty: 3,
    durationMin: 25,
    scenario: build("Data Exfiltration", {
      stations: [
        { id: "hq", name: "Command", role: "hq", module: "tracking" },
        { id: "term-1", name: "Target System", role: "element", module: "terminal" },
        { id: "vault-1", name: "Archive", role: "element", module: "terminal" },
        { id: "track-1", name: "Alpha 01", role: "element", module: "tracking", player: true, route },
        { id: "cam-1", name: "Camera 01", role: "element", module: "camera" },
      ],
      props: [
        {
          id: "payload-1",
          kind: "payload",
          name: "Data Core",
          states: ["empty", "copied", "destroyed"],
          initial: "empty",
          visible: true,
        },
      ],
      zones: [{ id: "zone-1", name: "Target Area", lat: 51.233, lng: 6.786, radius: 100 }],
      objectives: [
        { id: "obj-1", name: "Gain access" },
        { id: "obj-2", name: "Copy data" },
        { id: "obj-3", name: "Leave area" },
      ],
      injects: [
        {
          id: "inj-1",
          name: "Alarm",
          trigger: "timer",
          at: 300,
          actions: [{ type: "message", text: "Alarm in target area" }],
          enabled: true,
        },
      ],
    }),
  },
  {
    id: "beacon-activation",
    name: "Beacon Activation",
    summary: "Reach the target area, activate and hold the beacon.",
    category: "airsoft",
    difficulty: 2,
    durationMin: 20,
    scenario: build("Beacon Activation", {
      stations: [
        { id: "hq", name: "Command", role: "hq", module: "tracking" },
        {
          id: "beacon-1",
          name: "Beacon",
          role: "element",
          module: "beacon",
          bindings: { patient: "", prop: "beacon-1", objective: "" },
        },
        { id: "track-1", name: "Alpha 01", role: "element", module: "tracking", player: true, route },
        { id: "term-1", name: "Terminal", role: "element", module: "terminal" },
      ],
      props: [
        {
          id: "beacon-1",
          kind: "beacon",
          name: "Beacon 01",
          states: ["off", "active", "interference"],
          initial: "off",
          visible: true,
        },
      ],
      zones: [{ id: "zone-1", name: "Target Area", lat: 51.233, lng: 6.786, radius: 80 }],
      objectives: [
        { id: "obj-1", name: "Reach target area" },
        { id: "obj-2", name: "Activate beacon" },
        { id: "obj-3", name: "Hold signal" },
      ],
    }),
  },
  {
    id: "search-rescue",
    name: "Search & Rescue",
    summary: "Find, stabilise and evacuate a patient.",
    category: "airsoft",
    difficulty: 2,
    durationMin: 30,
    scenario: template("sar"),
  },
  {
    id: "medical-emergency",
    name: "Medical Emergency",
    summary: "Patient care without props.",
    category: "starter",
    difficulty: 1,
    durationMin: 15,
    scenario: build("Medical Emergency", {
      stations: [
        { id: "hq", name: "Command", role: "hq", module: "tracking" },
        {
          id: "med-1",
          name: "Medical 01",
          role: "element",
          module: "medical",
          bindings: { patient: "patient-1", prop: "", objective: "" },
        },
        { id: "term-1", name: "Records", role: "element", module: "terminal" },
      ],
      patients: [{ id: "patient-1", name: "Patient 01", kind: "trauma", since: 0 }],
      objectives: [{ id: "obj-1", name: "Treat patient" }],
    }),
  },
  {
    id: "access-lockdown",
    name: "Access & Lockdown",
    summary: "Gain access and lock down the area.",
    category: "starter",
    difficulty: 2,
    durationMin: 15,
    scenario: build("Access & Lockdown", {
      stations: [
        { id: "hq", name: "Command", role: "hq", module: "tracking" },
        { id: "acc-1", name: "Access", role: "element", module: "access" },
        { id: "lock-1", name: "Lockdown", role: "element", module: "lock" },
        { id: "term-1", name: "Terminal", role: "element", module: "terminal" },
      ],
      zones: [{ id: "zone-1", name: "Interior", lat: 51.233, lng: 6.786, radius: 60 }],
      objectives: [
        { id: "obj-1", name: "Gain access" },
        { id: "obj-2", name: "Secure area" },
      ],
    }),
  },
  {
    id: "milsim-skirmish",
    name: "MILSIM Skirmish",
    summary: "Two teams, one objective, no props.",
    category: "airsoft",
    difficulty: 2,
    durationMin: 20,
    scenario: build("MILSIM Skirmish", {
      stations: [
        { id: "hq", name: "Command", role: "hq", module: "tracking" },
        { id: "alpha-1", name: "Alpha 01", role: "element", module: "tracking", player: true, team: "ALPHA", route },
        { id: "bravo-1", name: "Bravo 01", role: "element", module: "tracking", player: true, team: "BRAVO", route },
        { id: "comms-1", name: "Radio", role: "element", module: "comms" },
      ],
      teams: [
        { id: "ALPHA", name: "Alpha", color: "#80dce5" },
        { id: "BRAVO", name: "Bravo", color: "#f36c75" },
      ],
      zones: [{ id: "zone-1", name: "Objective", lat: 51.233, lng: 6.786, radius: 90 }],
      objectives: [{ id: "obj-1", name: "Hold objective" }],
    }),
  },
  {
    id: "film-playback",
    name: "Film Playback",
    summary: "Two stage outputs without an exercise server.",
    category: "film",
    difficulty: 1,
    durationMin: 10,
    scenario: build("Film Playback", {
      mode: "PLAYBACK",
      stations: [
        { id: "stage-1", name: "Stage 01", role: "element", module: "intranet" },
        { id: "stage-2", name: "Stage 02", role: "element", module: "hologram" },
      ],
      objectives: [{ id: "obj-1", name: "Prepare sequence" }],
    }),
  },
  {
    id: "relay-recovery",
    name: "Relay Recovery",
    summary: "Restore a degraded relay with a player team and timed MEL events.",
    category: "airsoft",
    difficulty: 2,
    durationMin: 25,
    scenario: scenarioSchema.parse({
      version: 2,
      name: "Relay Recovery",
      mode: "LIVE",
      seed: 3117,
      map,
      stations: [
        { id: "hq", name: "HQ", role: "hq", module: "tracking" },
        {
          id: "op-a",
          name: "Operator A",
          role: "element",
          module: "tracking",
          player: true,
        },
        {
          id: "op-b",
          name: "Operator B",
          role: "element",
          module: "terminal",
          code: "4173",
        },
        {
          id: "relay",
          name: "Relay Terminal",
          role: "element",
          module: "data-sheet",
        },
      ],
      objectives: [{ id: "relay-online", name: "Activate relay" }],
      injects: [
        {
          id: "link-degrade",
          name: "Data link degraded",
          trigger: "timer",
          at: 180,
          category: "inject",
          purpose: "Use alternative information paths",
          expectedOutcome: ["comms.report"],
          evidence: ["Event: Data link degraded"],
          failurePolicy: "degrade",
          actions: [{ type: "message", text: "Data link unstable" }],
        },
        {
          id: "extra-release",
          name: "Additional release",
          trigger: "timer",
          at: 300,
          category: "contingency",
          purpose: "Verify the release process",
          expectedOutcome: ["access.requested"],
          evidence: ["Event: Additional release"],
          failurePolicy: "continue",
          actions: [{ type: "message", text: "Additional release required" }],
        },
        {
          id: "time-window",
          name: "Time window",
          trigger: "manual",
          category: "other",
          purpose: "Decide under time pressure",
          expectedOutcome: ["decision.request"],
          evidence: ["Event: Time window"],
          failurePolicy: "trainerDecision",
          actions: [{ type: "message", text: "Time window running" }],
        },
      ],
    }),
  },
  {
    id: "device-link",
    name: "Device Link & Diagnostics",
    summary:
      "Connect a fictional device, pass the code challenge, read diagnostics. The trainer provides the access code (default 7392).",
    category: "professional",
    difficulty: 2,
    durationMin: 10,
    scenario: scenarioSchema.parse({
      version: 2,
      name: "Device Link & Diagnostics",
      mode: "LIVE",
      seed: 1337,
      map,
      stations: [
        { id: "hq", name: "Command", role: "hq", module: "tracking" },
        {
          id: "device-1",
          name: "Device Console",
          role: "element",
          module: "terminal",
          bindings: { patient: "", prop: "device-alpha", objective: "" },
        },
      ],
      props: [
        {
          id: "device-alpha",
          kind: "custom",
          name: "Device alpha",
          states: ["disconnected", "connected", "diagnosed", "locked"],
          initial: "disconnected",
        },
      ],
      objectives: [{ id: "obj-diagnose", name: "Diagnose device" }],
      workflows: [
        {
          id: "wf-device-link",
          version: 1,
          name: "Device link",
          trigger: { type: "prop", prop: "device-alpha", to: "connected" },
          entry: "start",
          nodes: [
            { id: "start", type: "start" },
            {
              id: "link",
              type: "show-surface",
              station: "device-1",
              surface: "link",
            },
            {
              id: "code",
              type: "task",
              task: "code-entry",
              config: {
                expectedValueRef: "",
                maxAttempts: 3,
                inputLength: 4,
                maskInput: true,
              },
            },
            { id: "fail", type: "increment", variable: "attempts" },
            {
              id: "limit",
              type: "condition",
              variable: "attempts",
              operator: ">=",
              value: 3,
            },
            {
              id: "lockout",
              type: "show-surface",
              station: "device-1",
              surface: "lockout",
            },
            { id: "lockout-end", type: "end", outcome: "failure" },
            {
              id: "diagnostics",
              type: "show-surface",
              station: "device-1",
              surface: "diagnostics",
            },
            {
              id: "mark",
              type: "set-prop-state",
              prop: "device-alpha",
              state: "diagnosed",
            },
            {
              id: "done",
              type: "complete-objective",
              objective: "obj-diagnose",
            },
            { id: "end", type: "end", outcome: "success" },
          ],
          edges: [
            { id: "e1", source: "start", output: "out", target: "link" },
            { id: "e2", source: "link", output: "out", target: "code" },
            {
              id: "e3",
              source: "code",
              output: "success",
              target: "diagnostics",
            },
            { id: "e4", source: "code", output: "failure", target: "fail" },
            { id: "e5", source: "fail", output: "out", target: "limit" },
            { id: "e6", source: "limit", output: "true", target: "lockout" },
            { id: "e7", source: "limit", output: "false", target: "code" },
            {
              id: "e8",
              source: "lockout",
              output: "out",
              target: "lockout-end",
            },
            {
              id: "e9",
              source: "diagnostics",
              output: "out",
              target: "mark",
            },
            { id: "e10", source: "mark", output: "out", target: "done" },
            { id: "e11", source: "done", output: "out", target: "end" },
          ],
          variables: [{ id: "attempts", kind: "number", initial: 0 }],
        },
      ],
    }),
  },
  {
    id: "secure-transfer",
    name: "Secure Data Transfer",
    summary: "Scripted film playback with three manual beats.",
    category: "film",
    difficulty: 1,
    durationMin: 10,
    scenario: scenarioSchema.parse({
      version: 2,
      name: "Secure Data Transfer",
      mode: "PLAYBACK",
      seed: 7,
      map,
      stations: [
        { id: "hero", name: "Hero Terminal", role: "element", module: "terminal" },
        { id: "hq", name: "Director", role: "hq", module: "tracking" },
      ],
      objectives: [{ id: "transfer", name: "Transfer complete" }],
      injects: [
        {
          id: "beat-login",
          name: "Login",
          trigger: "manual",
          category: "expected_action",
          purpose: "Beat: login",
          expectedOutcome: ["identity.confirmed"],
          evidence: ["Event: Login"],
          failurePolicy: "hold",
          actions: [{ type: "message", text: "IDENTITY VERIFIED" }],
        },
        {
          id: "beat-warning",
          name: "Warning",
          trigger: "manual",
          category: "expected_action",
          purpose: "Beat: warning",
          expectedOutcome: ["warning.shown"],
          evidence: ["Event: Warning"],
          failurePolicy: "hold",
          actions: [{ type: "message", text: "INTEGRITY WARNING" }],
        },
        {
          id: "beat-transfer",
          name: "Transfer",
          trigger: "manual",
          category: "expected_action",
          purpose: "Beat: transfer",
          expectedOutcome: ["transfer.started"],
          evidence: ["Event: Transfer"],
          failurePolicy: "hold",
          actions: [{ type: "message", text: "TRANSFER RUNNING" }],
        },
      ],
    }),
  },
  {
    id: "distributed-command",
    name: "Distributed Command Incident",
    summary: "Multi-role incident with MEL events, zones and a casualty.",
    category: "professional",
    difficulty: 3,
    durationMin: 30,
    scenario: scenarioSchema.parse({
      version: 2,
      name: "Distributed Command Incident",
      mode: "LIVE",
      seed: 4096,
      map,
      stations: [
        { id: "hq", name: "Command", role: "hq", module: "tracking" },
        { id: "comms", name: "Comms", role: "element", module: "comms" },
        {
          id: "med-1",
          name: "Medic",
          role: "element",
          module: "medical",
          bindings: { patient: "patient-1" },
        },
        { id: "term-1", name: "Access", role: "element", module: "access" },
        {
          id: "op-1",
          name: "Team Alpha",
          role: "element",
          module: "tracking",
          player: true,
        },
      ],
      patients: [
        { id: "patient-1", name: "Casualty 01", kind: "stable", since: 0 },
      ],
      zones: [
        { id: "hazard", name: "Hazard Area", lat: 51.233, lng: 6.786, radius: 80 },
      ],
      objectives: [
        { id: "obj-intel", name: "Common picture confirmed" },
        { id: "obj-handover", name: "Handover complete" },
      ],
      injects: [
        {
          id: "source-conflict",
          name: "Sources contradict",
          trigger: "timer",
          at: 180,
          category: "inject",
          purpose: "Train information assessment",
          expectedOutcome: ["intel.flagged"],
          evidence: ["Event: Sources contradict"],
          failurePolicy: "continue",
          actions: [{ type: "message", text: "Source B contradicts Source A" }],
        },
        {
          id: "link-degrade",
          name: "Link Alpha degraded",
          trigger: "timer",
          at: 360,
          category: "inject",
          purpose: "Degraded operations",
          expectedOutcome: ["comms.report"],
          evidence: ["Event: Link Alpha degraded"],
          failurePolicy: "degrade",
          actions: [{ type: "message", text: "Link Alpha degraded" }],
        },
        {
          id: "casualty",
          name: "Casualty active",
          trigger: "manual",
          category: "inject",
          purpose: "Prioritisation and reporting",
          expectedOutcome: ["patient.assessed"],
          evidence: ["Event: Casualty active"],
          failurePolicy: "trainerDecision",
          actions: [{ type: "patient", target: "patient-1", kind: "trauma" }],
        },
        {
          id: "hazard",
          name: "Hazard reported",
          trigger: "zone",
          zone: "hazard",
          station: "op-1",
          category: "inject",
          purpose: "Isolation and specialist request",
          expectedOutcome: ["hazard.reported"],
          evidence: ["Event: Hazard reported"],
          fallback: "Controller message",
          failurePolicy: "branch",
          actions: [{ type: "message", text: "Suspicious object sighted" }],
        },
        {
          id: "handover",
          name: "Handover released",
          trigger: "manual",
          category: "expected_action",
          purpose: "Structured completion",
          expectedOutcome: ["handover.accepted"],
          evidence: ["Event: Handover released"],
          failurePolicy: "hold",
          actions: [{ type: "objective", target: "obj-handover" }],
        },
      ],
    }),
  },
];

export function buildMission(id: string): Scenario {
  const found = missionTemplates.find((t) => t.id === id);
  if (!found) throw new Error(`Unknown mission template: ${id}`);
  return structuredClone(found.scenario);
}
